server:
  port: 3306

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/Baemin?autoReconnect=true&serverTimezone=UTC&usdOldAliasMetadataBehavior=true# 변경해주세요
    username: root
    password:  qwert12345!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: comkauth.kakao.com.mysql.jdbc.Driver # mysql 5버전
